const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForSelector('#start-button', { timeout: 5000 });
  assert.match(await page.title(), /종선/);
  assert.equal(await page.locator('.burrow').count(), 7);
  fs.mkdirSync(path.resolve('artifacts'), { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop-ready.png', fullPage: true });
  await page.locator('#start-button').click();
  await page.waitForSelector('[data-status="playing"]', { timeout: 6000 });
  const target = page.locator('.burrow[data-phase="up"][data-kind="face"]').first();
  await target.waitFor({ state: 'visible' });
  const index = Number(await target.getAttribute('data-index'));
  await page.keyboard.press(String(index + 1));
  assert.ok(Number(await page.locator('#score').innerText()) >= 10, 'keyboard hit scores');
  await page.screenshot({ path: 'artifacts/desktop-hit.png', fullPage: true });
  await page.keyboard.press('p');
  assert.equal(await page.locator('#game').getAttribute('data-status'), 'paused');
  const frozen = await page.locator('#time').innerText();
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('#time').innerText(), frozen, 'pause freezes timer');
  await page.locator('#resume-button').click();
  await page.waitForSelector('[data-status="playing"]');
  await page.keyboard.press('Escape');
  await page.locator('#restart-button').click();
  await page.waitForSelector('[data-status="playing"]', { timeout: 6000 });
  assert.equal(await page.locator('#score').innerText(), '0');
  await page.locator('#sound-button').click();
  await page.locator('#sfx-toggle').uncheck();
  await page.locator('#music-toggle').uncheck();
  assert.equal(await page.locator('#sfx-toggle').isChecked(), false);
  await page.locator('#sound-button').click();
  await page.screenshot({ path: 'artifacts/desktop-playing.png', fullPage: true });

  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  phone.on('pageerror', error => errors.push(error.message));
  await phone.goto('http://127.0.0.1:4173/');
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile has no horizontal overflow');
  await phone.screenshot({ path: 'artifacts/mobile-ready.png', fullPage: true });
  await phone.locator('#start-button').tap();
  await phone.waitForSelector('[data-status="playing"]', { timeout: 6000 });
  const phoneFace = phone.locator('.burrow[data-phase="up"][data-kind="face"]').first();
  await phoneFace.tap();
  assert.ok(Number(await phone.locator('#score').innerText()) >= 10, 'touch scores');
  await phone.screenshot({ path: 'artifacts/mobile-playing.png', fullPage: true });
  assert.deepEqual(errors, [], 'no browser exceptions');
  await browser.close();
  console.log('PASS: desktop, keyboard hit, pause timer, resume, restart, sound controls, mobile fit and touch; zero browser exceptions.');
})().catch(error => { console.error(error); process.exit(1); });
